/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IntegersInterface extends ethers.utils.Interface {
  functions: {
    "load12x2(bytes1,bytes1,bytes1)": FunctionFragment;
    "load16(bytes1,bytes1)": FunctionFragment;
    "toString(uint256,uint8)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "load12x2",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "load16",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "toString",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "load12x2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "load16", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "toString", data: BytesLike): Result;

  events: {};
}

export class Integers extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IntegersInterface;

  functions: {
    load12x2(
      first: BytesLike,
      second: BytesLike,
      third: BytesLike,
      overrides?: CallOverrides
    ): Promise<[number, number]>;

    load16(
      _leadingBytes: BytesLike,
      _endingBytes: BytesLike,
      overrides?: CallOverrides
    ): Promise<[number]>;

    "toString(uint256,uint8)"(
      _number: BigNumberish,
      _base: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "toString(uint256)"(
      _number: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "toString(uint256,uint8,uint8)"(
      _number: BigNumberish,
      _base: BigNumberish,
      _padding: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  load12x2(
    first: BytesLike,
    second: BytesLike,
    third: BytesLike,
    overrides?: CallOverrides
  ): Promise<[number, number]>;

  load16(
    _leadingBytes: BytesLike,
    _endingBytes: BytesLike,
    overrides?: CallOverrides
  ): Promise<number>;

  "toString(uint256,uint8)"(
    _number: BigNumberish,
    _base: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "toString(uint256)"(
    _number: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "toString(uint256,uint8,uint8)"(
    _number: BigNumberish,
    _base: BigNumberish,
    _padding: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    load12x2(
      first: BytesLike,
      second: BytesLike,
      third: BytesLike,
      overrides?: CallOverrides
    ): Promise<[number, number]>;

    load16(
      _leadingBytes: BytesLike,
      _endingBytes: BytesLike,
      overrides?: CallOverrides
    ): Promise<number>;

    "toString(uint256,uint8)"(
      _number: BigNumberish,
      _base: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "toString(uint256)"(
      _number: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "toString(uint256,uint8,uint8)"(
      _number: BigNumberish,
      _base: BigNumberish,
      _padding: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    load12x2(
      first: BytesLike,
      second: BytesLike,
      third: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    load16(
      _leadingBytes: BytesLike,
      _endingBytes: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "toString(uint256,uint8)"(
      _number: BigNumberish,
      _base: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "toString(uint256)"(
      _number: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "toString(uint256,uint8,uint8)"(
      _number: BigNumberish,
      _base: BigNumberish,
      _padding: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    load12x2(
      first: BytesLike,
      second: BytesLike,
      third: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    load16(
      _leadingBytes: BytesLike,
      _endingBytes: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "toString(uint256,uint8)"(
      _number: BigNumberish,
      _base: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "toString(uint256)"(
      _number: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "toString(uint256,uint8,uint8)"(
      _number: BigNumberish,
      _base: BigNumberish,
      _padding: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
