/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IChainRunners, IChainRunnersInterface } from "../IChainRunners";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "getDna",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IChainRunners__factory {
  static readonly abi = _abi;
  static createInterface(): IChainRunnersInterface {
    return new utils.Interface(_abi) as IChainRunnersInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IChainRunners {
    return new Contract(address, _abi, signerOrProvider) as IChainRunners;
  }
}
