/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ICoBotsRenderer,
  ICoBotsRendererInterface,
} from "../ICoBotsRenderer";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "seed",
        type: "uint8",
      },
      {
        internalType: "bool",
        name: "status",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "color",
        type: "bool",
      },
    ],
    name: "tokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ICoBotsRenderer__factory {
  static readonly abi = _abi;
  static createInterface(): ICoBotsRendererInterface {
    return new utils.Interface(_abi) as ICoBotsRendererInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICoBotsRenderer {
    return new Contract(address, _abi, signerOrProvider) as ICoBotsRenderer;
  }
}
