/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IDreamersRenderer,
  IDreamersRendererInterface,
} from "../IDreamersRenderer";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "candy",
        type: "uint8",
      },
    ],
    name: "tokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IDreamersRenderer__factory {
  static readonly abi = _abi;
  static createInterface(): IDreamersRendererInterface {
    return new utils.Interface(_abi) as IDreamersRendererInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDreamersRenderer {
    return new Contract(address, _abi, signerOrProvider) as IDreamersRenderer;
  }
}
