/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  TypeAndVersionInterface,
  TypeAndVersionInterfaceInterface,
} from "../TypeAndVersionInterface";

const _abi = [
  {
    inputs: [],
    name: "typeAndVersion",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

export class TypeAndVersionInterface__factory {
  static readonly abi = _abi;
  static createInterface(): TypeAndVersionInterfaceInterface {
    return new utils.Interface(_abi) as TypeAndVersionInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TypeAndVersionInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as TypeAndVersionInterface;
  }
}
